version: "3.7"
services:
  test :
    build:
      context: ./..
      dockerfile: Local/dockerfile
    environment:
      browser: ${browser}
      country: ${country}
      environment: ${environment}
      remote_url: ${remote_url}
      remote_url_mob: ${remote_url_mob}
      test_cases: ${test_cases}
      test_suite: ${test_suite}
    user: ${HOST_UID_GID}
    volumes:
      - ${node_workspace_windows}:/tmp/results
    