version: "3"
services:
  test :
    build:
      context: ./..
      dockerfile: Local/dockerfile
    environment:
      browser: ${browser}
      country: ${country}
      environment: ${environment}
      remote_url: ${remote_url}
      test_cases: ${test_cases}
      test_suite: ${test_suite}
    user: ${HOST_UID_GID}
    volumes:
      - ${node_workspace_windows}:/tmp/results
    networks:
      - selenoid

networks:
  selenoid:
    external:
      name: tfg-elastest_selenoid