FROM python:3

WORKDIR /usr/src/app

COPY Jenkins/Environment/requirements.txt ./
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# We need wget to set up the PPA and xvfb to have a virtual screen and unzip to install the Chromedriver
RUN apt-get update
RUN apt-get install -y wget xvfb unzip

# Set up Chromedriver Environment variables
ENV CHROMEDRIVER_VERSION 80.0.3987.16
ENV CHROMEDRIVER_DIR /chromedriver
RUN mkdir $CHROMEDRIVER_DIR

# Download and install Chromedriver
RUN wget -q --continue -P $CHROMEDRIVER_DIR "http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
RUN unzip $CHROMEDRIVER_DIR/chromedriver* -d $CHROMEDRIVER_DIR

ENV browser=chrome
ENV country=es
ENV environment=DEV
ENV is_remote=True
ENV remote_url=http://selenoid:4444/wd/hub
ENV test_cases=""
ENV test_suite=M_login.robot

# Put Chromedriver into the PATH
ENV PATH $CHROMEDRIVER_DIR:$PATH
